### ISSUE TITLE
Any proxy is not splitting out dev ids with iOS app

### ISSUE THREAD

**Issue by razorRun** [codetheweb/tuyapi#247] opened 2019-09-01 12:41 UTC
Hi Guys 
I am not heting the list of IDs and Keys as mentioned in the instructions. I am getting a network unavailable error in tuya app. But I have configured certs properly.

Mobile is on IOS 
Any proxy latest running on a raspberry pi with node 10.11

**Comment by drhideg** [comment] 2019-09-01 16:24
I ran into the same error with an iobroker setup on debian and an android mobile. I had to downgrade debian's node10 to node8 from nodesource to get the keys. If you can, it's worth a try.

**Comment by codetheweb** [comment] 2019-09-01 22:05
Duplicate of https://github.com/codetheweb/tuyapi/issues/215.

**Closed by codetheweb** 2019-09-01 22:05 UTC
Labels: duplicate
