### ISSUE TITLE
TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by ShrileshKale** [codetheweb/tuyapi#315] opened 2020-04-30 18:45 UTC
I downloaded the tuyapi library using npm install codetheweb/tuyapi command and then went to tuapi folder and created tu.js file.

and pasted sample Asynchronous code from documentation ,just changed id and local key..
but after running it using node tu.js  i am getting the error that **Cannot read property '1' of undefined.**

Note - tuya plug device connects successfully.

![image](https://user-images.githubusercontent.com/13320662/80747211-5ab2b980-8b23-11ea-9287-210e5b487df9.png)

**Comment by codetheweb** [comment] 2020-04-30 21:22
Did you try `version: 3.3` in the constructor options?

**Comment by ShrileshKale** [comment] 2020-04-30 21:30
No.but can you help me with this?.. I did not anything except device id and key

**Comment by codetheweb** [comment] 2020-05-02 15:56
You could try acquiring the `key` again, as that's often the cause of the bad decode. Otherwise, you might have a [v3.2 device](https://github.com/codetheweb/tuyapi/issues/234).

**Comment by ShrileshKale** [comment] 2020-05-03 16:14
@codetheweb After looking for correct version , I could see the version 3.17.0 (international) in  app "Smart Life" .

Is it the right version i should look for? ..Is there any separate version for tuya  smart socket?

**Comment by codetheweb** [comment] 2020-05-03 22:14
There's not a great way to find the device version besides trial and error or listening to the device UDP broadcasts.  The second way can be accomplished if you omit the IP parameter in the constructor; TuyAPI should then automatically find the device and obtain the version.

**Comment by realjax** [comment] 2020-05-12 08:24
This is probably a duplicate of https://github.com/codetheweb/tuyapi/issues/246

**Comment by robertklep** [comment] 2020-11-22 11:22
FWIW, I had the same issue. When I used the files [in this gist](https://gist.github.com/SleepWalker/18f19679adbfacee6c415d4f6dc218bb) to list my device, it showed a different local key from the one I got with `tuya-cli link` (step 6 [from here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#linking-a-tuya-device-with-smart-link)).

**Closed** 2021-01-06 18:28 UTC
Labels: support
