### ISSUE TITLE
Error: getaddrinfo ENOTFOUND openapi.tuyaundefined.com

### ISSUE THREAD

**Issue by DmitryMaksakov** [codetheweb/tuyapi#496] opened 2021-07-06 12:50 UTC
**Describe the bug**
While trying to get device information, I am getting the `Error: getaddrinfo ENOTFOUND openapi.tuyaundefined.com`.

For some reason the tool tries to access openapi.tuya**undefined**.com

**To Reproduce**
`
> sudo tuya-cli wizard
? The API key from tuya.com: xxxx
? The API secret from tuya.com xxxx
? Provide a 'virtual ID' of a device currently registered in the app: xxxx
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
<ref *1> Error: getaddrinfo ENOTFOUND openapi.tuyaundefined.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'openapi.tuyaundefined.com',
  config: {
    url: 'https://openapi.tuyaundefined.com/v1.0/token?grant_type=1',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      t: '1625574613464',
      client_id: 'uwh3v8f4aqarkxdp5q2s',
      sign_method: 'HMAC-SHA256',
      sign: '04AD04EECB004ED5DB6C929A666A28F649C14C9F6CCF0557120B4DF62F82AA90',
      access_token: '',
...
`

**Expected behavior**
The tool should request correct address openapi.tuya<?>.com

**Debug Output**
The same as in To Reproduce section

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version 11.4 (20F71)
 - Node Version v16.4.2

**Additional context**
Maybe it somehow connected to 
> To better secure your cloud development, Tuya will upgrade the signature algorithm. Projects created after June 30, 2021 are subject to signature verification with the new algorithm. View details.
?

**Comment by tommitulpe** [comment] 2021-07-06 14:24
same issue here.

**Comment by randysnel** [comment] 2021-07-06 23:39
same issue on Ubuntu

**Comment by codetheweb** [comment] 2021-07-06 23:54
I am unable to reproduce this.

The wizard has been updated to use the latest signing algorithm.

Try clearing the configuration for @tuyapi/cli at `~/.config/configstore/@tuyapi/cli.json` on macOS (make sure to display it beforehand in case it turns out to be relevant).

**Comment by randysnel** [comment] 2021-07-07 00:00
For what its worth, I'm using Ubuntu 20.04 LTS and did a fresh instap through `npm i @tuyapi/cli -g` 

If you spin up a new VM with Ubuntu LTS it is reproduceable for sure, just validated it myself.

**Comment by codetheweb** [comment] 2021-07-07 00:54
Thanks for the suggestion.

I was able to reproduce. I believe this should be fixed in v1.17.1 of @tuyapi/cli, please upgrade and let me know.

**Comment by tommitulpe** [comment] 2021-07-07 06:39
Works perfectly now. Thanks a lot!

**Comment by DmitryMaksakov** [comment] 2021-07-07 09:40
Works fine, thank you for the fast fix!

**Closed** 2021-07-07 14:31 UTC
